# -*- coding: utf-8 -*-
"""Config video (opt-in) per l'articolo mutuo fisso vs variabile.
Esempio di riferimento: copia questo file per un nuovo articolo e adatta scene/testi."""

CONFIG = {
    "slug": "mutuo-fisso-o-variabile",
    "voice_id": "cjVigY5qzO86Huf0OWal",           # Eric (multilingua IT)
    "charts_dir": "public/charts/mutuo-fisso-o-variabile",
    "scenes": [
        {
            "type": "cover",
            "title": "Fisso o variabile?",
            "spark": {"top": "FISSO", "top_note": "rata bloccata 30 anni",
                      "bot": "VARIABILE", "bot_note": "segue l'Euribor / BCE"},
            "chip": "26 anni di dati BCE · Monte Carlo a 30 anni",
            "narration": "Stai per firmare un mutuo, e devi scegliere: tasso fisso, o variabile? La risposta più onesta non è \"fisso\", né \"variabile\". È: dipende. E dipende da una cosa sola. Ce lo dicono ventisei anni di dati veri della Banca Centrale Europea.",
            "captions": ["Stai per firmare un mutuo: fisso o variabile?",
                          "La risposta onesta è: dipende. E da una cosa sola.",
                          "Ventisei anni di dati veri della BCE."],
        },
        {
            "type": "chart_side",
            "title": "I due mutui",
            "chart": "context_rates.png",
            "annos": [{"t": "Euribor → il VARIABILE", "c": "amber", "at": 0.6, "y": 356},
                       {"t": "Mercato a lungo → il FISSO", "c": "navy", "at": 1.2, "y": 438}],
            "box": {"kicker": "IL PREMIO", "lines": ["quanto il fisso costa", "più del variabile."], "at": 2.2, "y": 545},
            "narration": "Il variabile segue l'Euribor, e quindi la Banca Centrale, quasi in tempo reale. Il fisso, invece, blocca la rata per trent'anni: ma parte da un tasso che incorpora già i rialzi che il mercato si aspetta, più un premio per la certezza. Ecco il punto che quasi tutti saltano: scegliere il variabile non significa scommettere che i tassi restino bassi, ma che restino più bassi di quanto il mercato già prevede. È una scommessa contro la curva.",
            "captions": ["Il variabile segue l'Euribor, quindi la BCE.",
                          "Il fisso blocca la rata, ma incorpora già i rialzi attesi.",
                          "Scegliere il variabile è scommettere contro la curva."],
        },
        {
            "type": "chart_side",
            "title": "Due epoche",
            "chart": "cohorts_payment.png",
            "annos": [{"t": "2000–2015", "c": "amber", "at": 0.6, "y": 360, "size": 42, "note": "→ vince il VARIABILE"},
                       {"t": "2016–2022", "c": "navy", "at": 1.4, "y": 500, "size": 42, "note": "→ vince il FISSO"}],
            "bignum": {"t": "+71%", "c": "amber", "at": 2.4, "y": 624, "note": "rata variabile, coorte 2021"},
            "narration": "Chi ha firmato tra il duemila e il duemilaquindici ha quasi sempre fatto meglio col variabile: partiva quando il fisso costava molto di più, e i tassi sono scesi per anni. Chi ha firmato tra il duemilasedici e il duemilaventidue, invece, ha fatto meglio col fisso: la curva era piatta, il fisso costava quasi come il variabile. Un'assicurazione quasi gratis. Poi è arrivato lo shock del duemilaventidue: chi era a variabile nel duemilaventuno ha visto la rata salire del settantuno per cento in poco più di un anno. Chi aveva il fisso, non ha visto muoversi un centesimo.",
            "captions": ["2000–2015: quasi sempre meglio il variabile.",
                          "2016–2022: meglio il fisso, con la curva piatta.",
                          "Shock 2022: chi era a variabile nel 2021, rata +71%.",
                          "Chi aveva il fisso non ha visto muoversi un centesimo."],
        },
        {
            "type": "stats",
            "heading": "10.000 mutui simulati su 30 anni",
            "items": [{"big": "2", "suffix": " su 3", "note": "scenari in cui il VARIABILE costa meno", "c": "navy", "at": 0.6},
                       {"countup": -34000, "fmt": "eur", "note": "risparmio mediano (mutuo 200.000 €)", "c": "amber", "at": 1.4}],
            "inset": "mc_cost_distribution.png",
            "narration": "Ma nessun mutuo dell'era dell'euro ha ancora compiuto trent'anni. Così ne abbiamo simulati diecimila, ricostruendo i tassi dalla storia reale. Sul puro costo, vince il variabile: costa meno in due scenari su tre, con un risparmio mediano di circa trentaquattromila euro su un mutuo da duecentomila. Il premio del fisso, in media, non viene ripagato.",
            "captions": ["Nessun mutuo dell'era dell'euro ha ancora 30 anni.",
                          "Allora ne simuliamo 10.000, dai tassi reali.",
                          "Sul costo vince il variabile: meno in 2 casi su 3.",
                          "Risparmio mediano ≈ 34.000 € su 200.000 €."],
        },
        {
            "type": "risk_bars",
            "heading": "L'altra metà: il rischio",
            "pct": 74,
            "pct_note": ["delle volte la rata del variabile", "prima o poi supera quella del fisso"],
            "highlight": "1 caso su 3 → oltre +30% di rata",
            "bars": {"a": 676, "b": 1150, "a_label": "2021", "b_label": "2023", "pct": "+71%",
                      "title": "la rata reale di chi ha firmato nel 2021"},
            "narration": "In media. Perché il rischio racconta l'altra metà della storia: nel settantaquattro per cento degli scenari, prima o poi, la rata del variabile supera quella del fisso; e in un caso su tre la supera di oltre il trenta per cento. Il fisso non è più caro: è un'assicurazione. E il premio che paghi, lo recuperi proprio in quegli scenari difficili.",
            "captions": ["Ma il rischio è l'altra metà della storia.",
                          "Nel 74% la rata del variabile supera quella del fisso.",
                          "In 1 caso su 3 la supera di oltre il 30%.",
                          "Il fisso non è più caro: è un'assicurazione."],
        },
        {
            "type": "transform_chart",
            "heading": "La surroga: l'arma segreta del fisso",
            "from": "34%", "from_note": "senza surroga",
            "to": "57%", "to_note": "con surroga (gratis dal 2007)",
            "footer": "probabilità che il FISSO costi meno del variabile",
            "chart": "mc_pfisso_vs_spread.png",
            "chart_caption": "a decidere è il premio iniziale del fisso (riga rossa = oggi)",
            "split": 0.52,
            "narration": "E qui arriva l'arma segreta del fisso, che quasi nessuno considera: la surroga. In Italia, dal duemilasette, rifinanziare il mutuo a un tasso più basso è gratis. Dà al fisso un'opzione a senso unico: se i tassi scendono ti riabbassi, se salgono stai fermo. Con la surroga, la probabilità che il fisso costi meno del variabile passa dal trentaquattro al cinquantasette per cento: diventa maggioranza. Ma ciò che decide davvero è un solo numero: il premio iniziale. Quanto costa in più il fisso, il giorno in cui firmi.",
            "captions": ["L'arma segreta del fisso: la surroga, gratis dal 2007.",
                          "Tassi giù ti riabbassi, tassi su stai fermo.",
                          "Con la surroga il fisso costa meno: dal 34% al 57%.",
                          "A decidere è il premio iniziale del fisso."],
        },
        {
            "type": "rates_today",
            "heading": "E oggi? (metà 2026)",
            "left": {"label": "FISSO", "val": "3,56%"},
            "right": {"label": "VARIABILE", "val": "2,99%"},
            "badge": "premio +0,57 punti · moderato",
            "line_countup": {"pct": 60, "tpl": "con surroga, oggi il fisso vince nel {v}%"},
            "cta": "Studio completo + simulatore su smartmoneylab.it",
            "narration": "E oggi? A metà duemilaventisei il fisso costa lo zero virgola cinquantasette per cento in più del variabile: un premio moderato. A questo livello, con la surroga, il fisso torna in vantaggio nel sessanta per cento degli scenari. La bilancia pende leggermente verso il fisso. Ma resta una scommessa sul percorso della Banca Centrale, non una previsione. Sul blog trovi lo studio completo, e un simulatore per provarlo sui tuoi numeri.",
            "captions": ["Oggi: fisso 3,56% contro variabile 2,99%.",
                          "Un premio di +0,57 punti: moderato.",
                          "Con la surroga, oggi il fisso vince nel 60%.",
                          "Non è una previsione: dipende dalla BCE."],
        },
        {
            "type": "outro",
            "narration": "SmartMoneyLab. Finanza personale, e analisi quantitativa.",
            "captions": [],
        },
    ],
}
